/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package photogrammetrie;

public class BPoint extends Point {
  private long swigCPtr;

  protected BPoint(long cPtr, boolean cMemoryOwn) {
    super(photoJNI.SWIGBPointUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BPoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      photoJNI.delete_BPoint(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public BPoint(Cam C) {
    this(photoJNI.new_BPoint__SWIG_0(Cam.getCPtr(C), C), true);
  }

  public BPoint(Cam C, double m, double n) {
    this(photoJNI.new_BPoint__SWIG_1(Cam.getCPtr(C), C, m, n), true);
  }

  public BPoint(Cam C, double x, double y, double z) {
    this(photoJNI.new_BPoint__SWIG_2(Cam.getCPtr(C), C, x, y, z), true);
  }

  public void set_mnPixKoo(double m, double n) {
    photoJNI.BPoint_set_mnPixKoo(swigCPtr, this, m, n);
  }

  public void set_xyBKoo(double x, double y) {
    photoJNI.BPoint_set_xyBKoo(swigCPtr, this, x, y);
  }

  public void set_XYZObjKoo(double X, double Y, double Z) {
    photoJNI.BPoint_set_XYZObjKoo(swigCPtr, this, X, Y, Z);
  }

  public BPoint(BPoint A) {
    this(photoJNI.new_BPoint__SWIG_3(BPoint.getCPtr(A), A), true);
  }

  public Cam get_Cam() {
    return new Cam(photoJNI.BPoint_get_Cam(swigCPtr, this), true);
  }

  public Cam get_Cam_Ref() {
    return new Cam(photoJNI.BPoint_get_Cam_Ref(swigCPtr, this), false);
  }

  public double get_m() {
    return photoJNI.BPoint_get_m(swigCPtr, this);
  }

  public double get_n() {
    return photoJNI.BPoint_get_n(swigCPtr, this);
  }

  public double get_X() {
    return photoJNI.BPoint_get_X(swigCPtr, this);
  }

  public double get_Y() {
    return photoJNI.BPoint_get_Y(swigCPtr, this);
  }

  public double get_Z() {
    return photoJNI.BPoint_get_Z(swigCPtr, this);
  }

  public Point get_Point() {
    return new Point(photoJNI.BPoint_get_Point(swigCPtr, this), true);
  }

  public Point get_xyBKooKorr() {
    return new Point(photoJNI.BPoint_get_xyBKooKorr(swigCPtr, this), true);
  }

  public Point get_xyBKoo() {
    return new Point(photoJNI.BPoint_get_xyBKoo(swigCPtr, this), true);
  }

  public BPoint get_KernlinenPunkt(Cam C, double s) {
    return new BPoint(photoJNI.BPoint_get_KernlinenPunkt(swigCPtr, this, Cam.getCPtr(C), C, s), true);
  }

}
