/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package photogrammetrie;

public class Cam {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Cam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      photoJNI.delete_Cam(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Cam() {
    this(photoJNI.new_Cam__SWIG_0(), true);
  }

  public Cam(double pix_row, double pix_col, double pix_size, double OX, double OY, double OZ, double rotX, double rotY, double rotZ, double c, double xh, double yh, double A1, double A2, double A3, double B1, double B2, double C1, double C2, double r0) {
    this(photoJNI.new_Cam__SWIG_1(pix_row, pix_col, pix_size, OX, OY, OZ, rotX, rotY, rotZ, c, xh, yh, A1, A2, A3, B1, B2, C1, C2, r0), true);
  }

  public Cam(Cam C) {
    this(photoJNI.new_Cam__SWIG_2(Cam.getCPtr(C), C), true);
  }

  public double get_pix_row() {
    return photoJNI.Cam_get_pix_row(swigCPtr, this);
  }

  public double get_pix_col() {
    return photoJNI.Cam_get_pix_col(swigCPtr, this);
  }

  public double get_pix_size() {
    return photoJNI.Cam_get_pix_size(swigCPtr, this);
  }

  public Point get_O() {
    return new Point(photoJNI.Cam_get_O(swigCPtr, this), true);
  }

  public double get_OX() {
    return photoJNI.Cam_get_OX(swigCPtr, this);
  }

  public double get_OY() {
    return photoJNI.Cam_get_OY(swigCPtr, this);
  }

  public double get_OZ() {
    return photoJNI.Cam_get_OZ(swigCPtr, this);
  }

  public double get_rotX() {
    return photoJNI.Cam_get_rotX(swigCPtr, this);
  }

  public double get_rotY() {
    return photoJNI.Cam_get_rotY(swigCPtr, this);
  }

  public double get_rotZ() {
    return photoJNI.Cam_get_rotZ(swigCPtr, this);
  }

  public double get_c() {
    return photoJNI.Cam_get_c(swigCPtr, this);
  }

  public double get_xh() {
    return photoJNI.Cam_get_xh(swigCPtr, this);
  }

  public double get_yh() {
    return photoJNI.Cam_get_yh(swigCPtr, this);
  }

  public double get_A1() {
    return photoJNI.Cam_get_A1(swigCPtr, this);
  }

  public double get_A2() {
    return photoJNI.Cam_get_A2(swigCPtr, this);
  }

  public double get_A3() {
    return photoJNI.Cam_get_A3(swigCPtr, this);
  }

  public double get_B1() {
    return photoJNI.Cam_get_B1(swigCPtr, this);
  }

  public double get_B2() {
    return photoJNI.Cam_get_B2(swigCPtr, this);
  }

  public double get_C1() {
    return photoJNI.Cam_get_C1(swigCPtr, this);
  }

  public double get_C2() {
    return photoJNI.Cam_get_C2(swigCPtr, this);
  }

  public double get_r0() {
    return photoJNI.Cam_get_r0(swigCPtr, this);
  }

  public void set_rotX(double rotX) {
    photoJNI.Cam_set_rotX(swigCPtr, this, rotX);
  }

  public void set_rotY(double rotY) {
    photoJNI.Cam_set_rotY(swigCPtr, this, rotY);
  }

  public void set_rotZ(double rotZ) {
    photoJNI.Cam_set_rotZ(swigCPtr, this, rotZ);
  }

  public void set_O(Point P) {
    photoJNI.Cam_set_O(swigCPtr, this, Point.getCPtr(P), P);
  }

  public SWIGTYPE_p_Matrix TransInRellativeOrientierung(Cam C_l, Cam C_r, Cam C_l_rell, Cam C_r_rell) {
    return new SWIGTYPE_p_Matrix(photoJNI.Cam_TransInRellativeOrientierung(swigCPtr, this, Cam.getCPtr(C_l), C_l, Cam.getCPtr(C_r), C_r, Cam.getCPtr(C_l_rell), C_l_rell, Cam.getCPtr(C_r_rell), C_r_rell), true);
  }

  public boolean read_from_ini(String datname) {
    return photoJNI.Cam_read_from_ini(swigCPtr, this, datname);
  }

  public boolean write_in_ini(String datname) {
    return photoJNI.Cam_write_in_ini(swigCPtr, this, datname);
  }

}
