/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package photogrammetrie;

public class CBPointList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CBPointList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CBPointList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      photoJNI.delete_CBPointList(swigCPtr);
    }
    swigCPtr = 0;
  }

  public CBPointList() {
    this(photoJNI.new_CBPointList(), true);
  }

  public void addBPoint(BPoint bp) {
    photoJNI.CBPointList_addBPoint(swigCPtr, this, BPoint.getCPtr(bp), bp);
  }

  public int size() {
    return photoJNI.CBPointList_size(swigCPtr, this);
  }

  public void clearBPointList() {
    photoJNI.CBPointList_clearBPointList(swigCPtr, this);
  }

  public void setM_BPoint_List(SWIGTYPE_p_vectorTBPoint_t value) {
    photoJNI.CBPointList_m_BPoint_List_set(swigCPtr, this, SWIGTYPE_p_vectorTBPoint_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorTBPoint_t getM_BPoint_List() {
    long cPtr = photoJNI.CBPointList_m_BPoint_List_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorTBPoint_t(cPtr, false);
  }

}
