/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package photogrammetrie;

class photoJNI {
  public final static native long new_Point__SWIG_0();
  public final static native long new_Point__SWIG_1(double jarg1, double jarg2, double jarg3);
  public final static native void delete_Point(long jarg1);
  public final static native double Point_get_X(long jarg1, Point jarg1_);
  public final static native double Point_get_Y(long jarg1, Point jarg1_);
  public final static native double Point_get_Z(long jarg1, Point jarg1_);
  public final static native double Point_get_dX(long jarg1, Point jarg1_);
  public final static native double Point_get_dY(long jarg1, Point jarg1_);
  public final static native double Point_get_dZ(long jarg1, Point jarg1_);
  public final static native long Point_get_dXYZ(long jarg1, Point jarg1_);
  public final static native long new_Point__SWIG_2(long jarg1, Point jarg1_);
  public final static native void Point_set_X(long jarg1, Point jarg1_, double jarg2);
  public final static native void Point_set_Y(long jarg1, Point jarg1_, double jarg2);
  public final static native void Point_set_Z(long jarg1, Point jarg1_, double jarg2);
  public final static native void Point_set_dX(long jarg1, Point jarg1_, double jarg2);
  public final static native void Point_set_dY(long jarg1, Point jarg1_, double jarg2);
  public final static native void Point_set_dZ(long jarg1, Point jarg1_, double jarg2);
  public final static native double Point_Quad(long jarg1, Point jarg1_);
  public final static native double Point_Betrag(long jarg1, Point jarg1_);
  public final static native long Point_Norm(long jarg1, Point jarg1_);
  public final static native double Point_Abstand(long jarg1, Point jarg1_, long jarg2, Point jarg2_);
  public final static native long Point_Add(long jarg1, Point jarg1_, long jarg2, Point jarg2_);
  public final static native long Point_Subt(long jarg1, Point jarg1_, long jarg2, Point jarg2_);
  public final static native double Point_Mult(long jarg1, Point jarg1_, long jarg2, Point jarg2_);
  public final static native long Point_MultS(long jarg1, Point jarg1_, double jarg2);
  public final static native long Point_DivS(long jarg1, Point jarg1_, double jarg2);
  public final static native long Point_SpatP(long jarg1, Point jarg1_, long jarg2, Point jarg2_);
  public final static native long Point_Rotation(long jarg1, Point jarg1_, long jarg2, Point jarg2_, long jarg3);
  public final static native long Point_RotationRueck(long jarg1, Point jarg1_, long jarg2, Point jarg2_, long jarg3);
  public final static native long new_BPoint__SWIG_0(long jarg1, Cam jarg1_);
  public final static native long new_BPoint__SWIG_1(long jarg1, Cam jarg1_, double jarg2, double jarg3);
  public final static native long new_BPoint__SWIG_2(long jarg1, Cam jarg1_, double jarg2, double jarg3, double jarg4);
  public final static native void BPoint_set_mnPixKoo(long jarg1, BPoint jarg1_, double jarg2, double jarg3);
  public final static native void BPoint_set_xyBKoo(long jarg1, BPoint jarg1_, double jarg2, double jarg3);
  public final static native void BPoint_set_XYZObjKoo(long jarg1, BPoint jarg1_, double jarg2, double jarg3, double jarg4);
  public final static native long new_BPoint__SWIG_3(long jarg1, BPoint jarg1_);
  public final static native long BPoint_get_Cam(long jarg1, BPoint jarg1_);
  public final static native long BPoint_get_Cam_Ref(long jarg1, BPoint jarg1_);
  public final static native double BPoint_get_m(long jarg1, BPoint jarg1_);
  public final static native double BPoint_get_n(long jarg1, BPoint jarg1_);
  public final static native double BPoint_get_X(long jarg1, BPoint jarg1_);
  public final static native double BPoint_get_Y(long jarg1, BPoint jarg1_);
  public final static native double BPoint_get_Z(long jarg1, BPoint jarg1_);
  public final static native long BPoint_get_Point(long jarg1, BPoint jarg1_);
  public final static native long BPoint_get_xyBKooKorr(long jarg1, BPoint jarg1_);
  public final static native long BPoint_get_xyBKoo(long jarg1, BPoint jarg1_);
  public final static native long BPoint_get_KernlinenPunkt(long jarg1, BPoint jarg1_, long jarg2, Cam jarg2_, double jarg3);
  public final static native void delete_BPoint(long jarg1);
  public final static native long new_Cam__SWIG_0();
  public final static native long new_Cam__SWIG_1(double jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, double jarg8, double jarg9, double jarg10, double jarg11, double jarg12, double jarg13, double jarg14, double jarg15, double jarg16, double jarg17, double jarg18, double jarg19, double jarg20);
  public final static native void delete_Cam(long jarg1);
  public final static native long new_Cam__SWIG_2(long jarg1, Cam jarg1_);
  public final static native double Cam_get_pix_row(long jarg1, Cam jarg1_);
  public final static native double Cam_get_pix_col(long jarg1, Cam jarg1_);
  public final static native double Cam_get_pix_size(long jarg1, Cam jarg1_);
  public final static native long Cam_get_O(long jarg1, Cam jarg1_);
  public final static native double Cam_get_OX(long jarg1, Cam jarg1_);
  public final static native double Cam_get_OY(long jarg1, Cam jarg1_);
  public final static native double Cam_get_OZ(long jarg1, Cam jarg1_);
  public final static native double Cam_get_rotX(long jarg1, Cam jarg1_);
  public final static native double Cam_get_rotY(long jarg1, Cam jarg1_);
  public final static native double Cam_get_rotZ(long jarg1, Cam jarg1_);
  public final static native double Cam_get_c(long jarg1, Cam jarg1_);
  public final static native double Cam_get_xh(long jarg1, Cam jarg1_);
  public final static native double Cam_get_yh(long jarg1, Cam jarg1_);
  public final static native double Cam_get_A1(long jarg1, Cam jarg1_);
  public final static native double Cam_get_A2(long jarg1, Cam jarg1_);
  public final static native double Cam_get_A3(long jarg1, Cam jarg1_);
  public final static native double Cam_get_B1(long jarg1, Cam jarg1_);
  public final static native double Cam_get_B2(long jarg1, Cam jarg1_);
  public final static native double Cam_get_C1(long jarg1, Cam jarg1_);
  public final static native double Cam_get_C2(long jarg1, Cam jarg1_);
  public final static native double Cam_get_r0(long jarg1, Cam jarg1_);
  public final static native void Cam_set_rotX(long jarg1, Cam jarg1_, double jarg2);
  public final static native void Cam_set_rotY(long jarg1, Cam jarg1_, double jarg2);
  public final static native void Cam_set_rotZ(long jarg1, Cam jarg1_, double jarg2);
  public final static native void Cam_set_O(long jarg1, Cam jarg1_, long jarg2, Point jarg2_);
  public final static native long Cam_TransInRellativeOrientierung(long jarg1, Cam jarg1_, long jarg2, Cam jarg2_, long jarg3, Cam jarg3_, long jarg4, Cam jarg4_, long jarg5, Cam jarg5_);
  public final static native boolean Cam_read_from_ini(long jarg1, Cam jarg1_, String jarg2);
  public final static native boolean Cam_write_in_ini(long jarg1, Cam jarg1_, String jarg2);
  public final static native long new_CBPointList();
  public final static native void delete_CBPointList(long jarg1);
  public final static native void CBPointList_addBPoint(long jarg1, CBPointList jarg1_, long jarg2, BPoint jarg2_);
  public final static native int CBPointList_size(long jarg1, CBPointList jarg1_);
  public final static native void CBPointList_clearBPointList(long jarg1, CBPointList jarg1_);
  public final static native void CBPointList_m_BPoint_List_set(long jarg1, CBPointList jarg1_, long jarg2);
  public final static native long CBPointList_m_BPoint_List_get(long jarg1, CBPointList jarg1_);
  public final static native long new_Vorwaertsschnitt_java();
  public final static native long Vorwaertsschnitt_java_calc_vorwaertsschnitt(long jarg1, Vorwaertsschnitt_java jarg1_, long jarg2, CBPointList jarg2_);
  public final static native void delete_Vorwaertsschnitt_java(long jarg1);
  public final static native long SWIGBPointUpcast(long jarg1);
}
