/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package photogrammetrie;

public class Vorwaertsschnitt_java {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Vorwaertsschnitt_java(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vorwaertsschnitt_java obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      photoJNI.delete_Vorwaertsschnitt_java(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Vorwaertsschnitt_java() {
    this(photoJNI.new_Vorwaertsschnitt_java(), true);
  }

  public Point calc_vorwaertsschnitt(CBPointList blist) {
    return new Point(photoJNI.Vorwaertsschnitt_java_calc_vorwaertsschnitt(swigCPtr, this, CBPointList.getCPtr(blist), blist), true);
  }

}
